# Generated by Django 5.2.8 on 2026-02-20 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_defaults(apps, schema_editor):
    Achievement = apps.get_model('events', 'Achievement')
    ChatChannel = apps.get_model('events', 'ChatChannel')
    ChatChannelMembership = apps.get_model('events', 'ChatChannelMembership')
    Event = apps.get_model('events', 'Event')
    EventRegistration = apps.get_model('events', 'EventRegistration')

    defaults = [
        {
            'slug': 'first_event',
            'title': 'Первый шаг',
            'description': 'Завершено первое событие',
            'icon': '🌱',
            'category': 'events_completed',
            'threshold': 1,
        },
        {
            'slug': 'five_events',
            'title': 'Активный участник',
            'description': 'Завершено 5 событий',
            'icon': '🔥',
            'category': 'events_completed',
            'threshold': 5,
        },
        {
            'slug': 'ten_events',
            'title': 'Опора команды',
            'description': 'Завершено 10 событий',
            'icon': '🏆',
            'category': 'events_completed',
            'threshold': 10,
        },
        {
            'slug': 'xp_250',
            'title': 'Набираю темп',
            'description': 'Получено 250 XP',
            'icon': '⚡',
            'category': 'xp_total',
            'threshold': 250,
        },
        {
            'slug': 'xp_1000',
            'title': 'Мастер волонтерства',
            'description': 'Получено 1000 XP',
            'icon': '👑',
            'category': 'xp_total',
            'threshold': 1000,
        },
    ]

    for item in defaults:
        Achievement.objects.get_or_create(
            slug=item['slug'],
            defaults={
                'title': item['title'],
                'description': item['description'],
                'icon': item['icon'],
                'category': item['category'],
                'threshold': item['threshold'],
                'is_active': True,
            },
        )

    for event in Event.objects.all():
        channel, _ = ChatChannel.objects.get_or_create(
            event=event,
            name='Общий',
            defaults={
                'topic': 'Основной канал события',
                'created_by_id': event.organizer_id,
            },
        )
        ChatChannelMembership.objects.get_or_create(channel=channel, user_id=event.organizer_id)

        approved_volunteers = EventRegistration.objects.filter(
            event_id=event.id,
            status__in=['approved', 'completed'],
        ).values_list('volunteer_id', flat=True)
        for volunteer_id in approved_volunteers:
            ChatChannelMembership.objects.get_or_create(channel=channel, user_id=volunteer_id)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('icon', models.CharField(default='🏅', max_length=10, verbose_name='Бейдж')),
                ('category', models.CharField(choices=[('events_completed', 'Завершенные события'), ('xp_total', 'Суммарный XP')], max_length=30, verbose_name='Категория')),
                ('threshold', models.PositiveIntegerField(default=1, verbose_name='Порог')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['category', 'threshold'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('community', 'Сообщество'), ('education', 'Образование'), ('ecology', 'Экология'), ('health', 'Здоровье'), ('charity', 'Благотворительность'), ('other', 'Другое')], db_index=True, default='community', max_length=30, verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='event',
            name='xp_reward',
            field=models.PositiveIntegerField(default=50, verbose_name='XP за участие'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='xp_awarded',
            field=models.BooleanField(default=False, verbose_name='XP начислен'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт (XP)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_volunteers',
            field=models.PositiveIntegerField(default=10, verbose_name='Макс. волонтеров'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('completed', 'Завершено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_approved', 'Заявка одобрена'), ('application_rejected', 'Заявка отклонена'), ('new_application', 'Новая заявка'), ('new_event', 'Новое событие'), ('event_reminder', 'Напоминание о событии'), ('new_message', 'Новое сообщение в чате'), ('achievement_unlocked', 'Новое достижение'), ('level_up', 'Новый уровень')], max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('organizer', 'Организатор')], default='volunteer', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название канала')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_channels', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='events.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Канал чата',
                'verbose_name_plural': 'Каналы чата',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее чтение')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Вступил')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.chatchannel', verbose_name='Канал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник канала',
                'verbose_name_plural': 'Участники каналов',
                'ordering': ['-joined_at'],
                'unique_together': {('channel', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='participants',
            field=models.ManyToManyField(related_name='chat_channels', through='events.ChatChannelMembership', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Изменено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.chatchannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.achievement', verbose_name='Достижение')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Полученное достижение',
                'verbose_name_plural': 'Полученные достижения',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatchannel',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_channel_name_per_event'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['channel', 'created_at'], name='events_chat_channel_35d6c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='volunteerachievement',
            unique_together={('volunteer', 'achievement')},
        ),
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
