# Generated by Django 5.2.8 on 2026-02-20 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_achievement_event_event_type_event_xp_reward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['category', 'threshold'], 'verbose_name': 'Р”РѕСЃС‚РёР¶РµРЅРёРµ', 'verbose_name_plural': 'Р”РѕСЃС‚РёР¶РµРЅРёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='chatchannel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'РљР°РЅР°Р» С‡Р°С‚Р°', 'verbose_name_plural': 'РљР°РЅР°Р»С‹ С‡Р°С‚Р°'},
        ),
        migrations.AlterModelOptions(
            name='chatchannelmembership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'РЈС‡Р°СЃС‚РЅРёРє РєР°РЅР°Р»Р°', 'verbose_name_plural': 'РЈС‡Р°СЃС‚РЅРёРєРё РєР°РЅР°Р»РѕРІ'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'РЎРѕРѕР±С‰РµРЅРёРµ', 'verbose_name_plural': 'РЎРѕРѕР±С‰РµРЅРёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time'], 'verbose_name': 'РЎРѕР±С‹С‚РёРµ', 'verbose_name_plural': 'РЎРѕР±С‹С‚РёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Р—Р°СЏРІРєР° РЅР° СЃРѕР±С‹С‚РёРµ', 'verbose_name_plural': 'Р—Р°СЏРІРєРё РЅР° СЃРѕР±С‹С‚РёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'РЈРІРµРґРѕРјР»РµРЅРёРµ', 'verbose_name_plural': 'РЈРІРµРґРѕРјР»РµРЅРёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'РќР°РІС‹Рє', 'verbose_name_plural': 'РќР°РІС‹РєРё'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'РџСЂРѕС„РёР»СЊ', 'verbose_name_plural': 'РџСЂРѕС„РёР»Рё'},
        ),
        migrations.AlterModelOptions(
            name='volunteerachievement',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'РџРѕР»СѓС‡РµРЅРЅРѕРµ РґРѕСЃС‚РёР¶РµРЅРёРµ', 'verbose_name_plural': 'РџРѕР»СѓС‡РµРЅРЅС‹Рµ РґРѕСЃС‚РёР¶РµРЅРёСЏ'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('events_completed', 'Р—Р°РІРµСЂС€РµРЅРЅС‹Рµ СЃРѕР±С‹С‚РёСЏ'), ('xp_total', 'РЎСѓРјРјР°СЂРЅС‹Р№ XP')], max_length=30, verbose_name='РљР°С‚РµРіРѕСЂРёСЏ'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='рџЏ…', max_length=10, verbose_name='Р‘РµР№РґР¶'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='РђРєС‚РёРІРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='РљРѕРґ'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='threshold',
            field=models.PositiveIntegerField(default=1, verbose_name='РџРѕСЂРѕРі'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=120, verbose_name='РќР°Р·РІР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅ'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_channels', to=settings.AUTH_USER_MODEL, verbose_name='РЎРѕР·РґР°РЅ РїРѕР»СЊР·РѕРІР°С‚РµР»РµРј'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='events.event', verbose_name='РЎРѕР±С‹С‚РёРµ'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='РђСЂС…РёРІРЅС‹Р№'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='name',
            field=models.CharField(max_length=120, verbose_name='РќР°Р·РІР°РЅРёРµ РєР°РЅР°Р»Р°'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='participants',
            field=models.ManyToManyField(related_name='chat_channels', through='events.ChatChannelMembership', to=settings.AUTH_USER_MODEL, verbose_name='РЈС‡Р°СЃС‚РЅРёРєРё'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='РўРµРјР°'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='РћР±РЅРѕРІР»РµРЅ'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.chatchannel', verbose_name='РљР°РЅР°Р»'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р’СЃС‚СѓРїРёР»'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='РџРѕСЃР»РµРґРЅРµРµ С‡С‚РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='РЈРІРµРґРѕРјР»РµРЅРёСЏ РІРєР»СЋС‡РµРЅС‹'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='РђРІС‚РѕСЂ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.chatchannel', verbose_name='РљР°РЅР°Р»'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='РЎРѕРѕР±С‰РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р\x98Р·РјРµРЅРµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Р“РѕСЂРѕРґ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Р”Р°С‚Р°'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('community', 'РЎРѕРѕР±С‰РµСЃС‚РІРѕ'), ('education', 'РћР±СЂР°Р·РѕРІР°РЅРёРµ'), ('ecology', 'Р\xadРєРѕР»РѕРіРёСЏ'), ('health', 'Р—РґРѕСЂРѕРІСЊРµ'), ('charity', 'Р‘Р»Р°РіРѕС‚РІРѕСЂРёС‚РµР»СЊРЅРѕСЃС‚СЊ'), ('other', 'Р”СЂСѓРіРѕРµ')], db_index=True, default='community', max_length=30, verbose_name='РўРёРї СЃРѕР±С‹С‚РёСЏ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL РёР·РѕР±СЂР°Р¶РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='РђРєС‚РёРІРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='РњРµСЃС‚Рѕ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_volunteers',
            field=models.PositiveIntegerField(default=10, verbose_name='РњР°РєСЃ. РІРѕР»РѕРЅС‚РµСЂРѕРІ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='РћСЂРіР°РЅРёР·Р°С‚РѕСЂ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.skill', verbose_name='РўСЂРµР±СѓРµРјС‹Рµ РЅР°РІС‹РєРё'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Р’СЂРµРјСЏ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='РќР°Р·РІР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='xp_reward',
            field=models.PositiveIntegerField(default=50, verbose_name='XP Р·Р° СѓС‡Р°СЃС‚РёРµ'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р—Р°РІРµСЂС€РµРЅРѕ РІ'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='РЎРѕР±С‹С‚РёРµ'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='message',
            field=models.TextField(blank=True, verbose_name='РЎРѕРѕР±С‰РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'РќР° СЂР°СЃСЃРјРѕС‚СЂРµРЅРёРё'), ('approved', 'РћРґРѕР±СЂРµРЅРѕ'), ('completed', 'Р—Р°РІРµСЂС€РµРЅРѕ'), ('rejected', 'РћС‚РєР»РѕРЅРµРЅРѕ'), ('cancelled', 'РћС‚РјРµРЅРµРЅРѕ')], default='pending', max_length=20, verbose_name='РЎС‚Р°С‚СѓСЃ'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Р’РѕР»РѕРЅС‚РµСЂ'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='xp_awarded',
            field=models.BooleanField(default=False, verbose_name='XP РЅР°С‡РёСЃР»РµРЅ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='РџСЂРѕС‡РёС‚Р°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='РЎРѕРѕР±С‰РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event', verbose_name='РЎРІСЏР·Р°РЅРЅРѕРµ СЃРѕР±С‹С‚РёРµ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.eventregistration', verbose_name='РЎРІСЏР·Р°РЅРЅР°СЏ Р·Р°СЏРІРєР°'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_approved', 'Р—Р°СЏРІРєР° РѕРґРѕР±СЂРµРЅР°'), ('application_rejected', 'Р—Р°СЏРІРєР° РѕС‚РєР»РѕРЅРµРЅР°'), ('new_application', 'РќРѕРІР°СЏ Р·Р°СЏРІРєР°'), ('new_event', 'РќРѕРІРѕРµ СЃРѕР±С‹С‚РёРµ'), ('event_reminder', 'РќР°РїРѕРјРёРЅР°РЅРёРµ Рѕ СЃРѕР±С‹С‚РёРё'), ('new_message', 'РќРѕРІРѕРµ СЃРѕРѕР±С‰РµРЅРёРµ РІ С‡Р°С‚Рµ'), ('achievement_unlocked', 'РќРѕРІРѕРµ РґРѕСЃС‚РёР¶РµРЅРёРµ'), ('level_up', 'РќРѕРІС‹Р№ СѓСЂРѕРІРµРЅСЊ')], max_length=50, verbose_name='РўРёРї СѓРІРµРґРѕРјР»РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Р\x98РєРѕРЅРєР°'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='РќР°Р·РІР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='РђРІР°С‚Р°СЂ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='РђРІР°С‚Р°СЂ URL (РѕРїС†РёРѕРЅР°Р»СЊРЅРѕ)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Рћ СЃРµР±Рµ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Р“РѕСЂРѕРґ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='РЈСЂРѕРІРµРЅСЊ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='РўРµР»РµС„РѕРЅ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Р’РѕР»РѕРЅС‚РµСЂ'), ('organizer', 'РћСЂРіР°РЅРёР·Р°С‚РѕСЂ')], default='volunteer', max_length=20, verbose_name='Р\xa0РѕР»СЊ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='events.skill', verbose_name='РќР°РІС‹РєРё'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='РћРїС‹С‚ (XP)'),
        ),
        migrations.AlterField(
            model_name='volunteerachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.achievement', verbose_name='Р”РѕСЃС‚РёР¶РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='volunteerachievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р’С‹РґР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='volunteerachievement',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Р’РѕР»РѕРЅС‚РµСЂ'),
        ),
    ]
