# Generated by Django 5.2.8 on 2026-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_achievement_event_event_type_event_xp_reward_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'date'], name='events_even_is_acti_85e9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city'], name='events_even_city_533bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_cdd3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['volunteer', 'status'], name='events_even_volunte_a5b15e_idx'),
        ),
    ]
