# Generated by Django 5.2.8 on 2026-03-08 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_achievement_options_alter_chatchannel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['category', 'threshold'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='chatchannel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Канал чата', 'verbose_name_plural': 'Каналы чата'},
        ),
        migrations.AlterModelOptions(
            name='chatchannelmembership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Участник канала', 'verbose_name_plural': 'Участники каналов'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на событие', 'verbose_name_plural': 'Заявки на события'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='volunteerachievement',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'Полученное достижение', 'verbose_name_plural': 'Полученные достижения'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('events_completed', 'Завершенные события'), ('xp_total', 'Суммарный XP')], max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏅', max_length=10, verbose_name='Бейдж'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='threshold',
            field=models.PositiveIntegerField(default=1, verbose_name='Порог'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_channels', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='events.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='participants',
            field=models.ManyToManyField(related_name='chat_channels', through='events.ChatChannelMembership', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.chatchannel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Вступил'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='last_read_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее чтение'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления включены'),
        ),
        migrations.AlterField(
            model_name='chatchannelmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.chatchannel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('community', 'Сообщество'), ('education', 'Образование'), ('ecology', 'Экология'), ('health', 'Здоровье'), ('charity', 'Благотворительность'), ('other', 'Другое')], db_index=True, default='community', max_length=30, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_volunteers',
            field=models.PositiveIntegerField(default=10, verbose_name='Макс. волонтеров'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.skill', verbose_name='Требуемые навыки'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='xp_reward',
            field=models.PositiveIntegerField(default=50, verbose_name='XP за участие'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено в'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('completed', 'Завершено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='xp_awarded',
            field=models.BooleanField(default=False, verbose_name='XP начислен'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event', verbose_name='Связанное событие'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.eventregistration', verbose_name='Связанная заявка'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_approved', 'Заявка одобрена'), ('application_rejected', 'Заявка отклонена'), ('new_application', 'Новая заявка'), ('new_event', 'Новое событие'), ('event_reminder', 'Напоминание о событии'), ('new_message', 'Новое сообщение в чате'), ('achievement_unlocked', 'Новое достижение'), ('level_up', 'Новый уровень')], max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='Аватар URL (опционально)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('organizer', 'Организатор')], default='volunteer', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='events.skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт (XP)'),
        ),
        migrations.AlterField(
            model_name='volunteerachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='events.achievement', verbose_name='Достижение'),
        ),
        migrations.AlterField(
            model_name='volunteerachievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Выдано'),
        ),
        migrations.AlterField(
            model_name='volunteerachievement',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
    ]
