databases:
  - name: volunteer-platform-db
    plan: free

services:
  - type: web
    name: volunteer-platform
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn volunteer.wsgi:application --log-file -
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: postgresql://volunteer_platform_db_9bkb_user:1Ecy7MrHO2yGxSFyjkYlcUik9Bkfge35@dpg-d6o6f5p5pdvs739t2ob0-a.frankfurt-postgres.render.com/volunteer_platform_db_9bkb
        fromDatabase:
          name: volunteer-platform-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "volunteer-platform-shwa.onrender.com,.onrender.com"
