# Generated by Django 6.0 on 2025-12-19 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('location', models.CharField(max_length=200, verbose_name='Место')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('max_volunteers', models.PositiveIntegerField(default=10, verbose_name='Макс. волонтёров')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='events', to='events.skill', verbose_name='Требуемые навыки')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('volunteer', 'Волонтёр'), ('organizer', 'Организатор')], default='volunteer', max_length=20, verbose_name='Роль')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('avatar', models.URLField(blank=True, verbose_name='Аватар URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='users', to='events.skill', verbose_name='Навыки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Событие')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Волонтёр')),
            ],
            options={
                'verbose_name': 'Заявка на событие',
                'verbose_name_plural': 'Заявки на события',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'volunteer')},
            },
        ),
    ]
